project: 
  type: website
  
website: 
  page-navigation: true
  title: "REU 2026 - Statistics Workshop" 
  description: "A hands-on R and Quarto statistics workshop for REU participants."
  site-url: "https://dharaden.github.io/REU_2026" 
  
  repo-url: https://github.com/dharaden/REU_2026
  repo-actions: [edit, issue]



  open-graph: true
  
  page-footer:
    right: "This page is built with ☕ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Dustin Haraden, 2026"
    background: "#3d3d3d"
    
  sidebar:
    background: "#3d3d3d"
    logo: "images/hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dharaden/REU_2026
        text: "GitHub"
        

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Overview"
      - section: "Sessions"
        contents:
          - href: sessions/1/index.qmd
            text: "Session 1"
          - href: sessions/2/index.qmd
            text: "Session 2"
          - href: sessions/X/index.qmd
            text: "Extra Materials"
      - href: materials.qmd
        text: "Materials"
      - href: resources.qmd
        text: "Additional Stuff"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual


filters:
  - include-files.lua
  - quarto

  
